In [16]:
a=10
a


10

In [7]:
a=10
b=20
print(a)
print(b)


10
20


In [24]:
a=[22,33,44,55]
a

[22, 33, 44, 55]

In [26]:
import numpy as np
score=np.array(a)
score 

array([22, 33, 44, 55])

In [27]:
d=np.mean(score)
d

np.float64(38.5)

In [29]:
print(np.max(score))
      

55


In [30]:
print(np.min(score))


22


In [33]:
f=np.zeros([3,3])
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
f=np.ones([4,5])
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
g=np.random.rand(5,5)
g

array([[9.54651563e-05, 4.58825061e-01, 2.73203144e-01, 4.47469182e-01,
        2.43058002e-01],
       [8.48631641e-01, 9.86680297e-01, 2.70345113e-01, 2.23438981e-01,
        7.64038834e-01],
       [6.95966598e-01, 3.72112270e-01, 5.83495648e-01, 2.44909496e-01,
        7.43283911e-01],
       [1.22344478e-01, 3.22833483e-01, 5.22072901e-01, 8.31739049e-01,
        2.94070693e-02],
       [1.99309718e-01, 3.91354126e-01, 6.49573866e-01, 7.92588203e-01,
        6.39466086e-01]])

In [41]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a.reshape([2,5])



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
b=np.arange(8).reshape(4,2)
b


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [56]:
c=np.array([11,22,44,65,2,56,9,5,3,6,3,6,])
c[1:4]

array([22, 44, 65])

In [58]:
c[1::2]

array([22, 65, 56,  5,  6,  6])

In [66]:
a=np.array([5,15,20])
b=np.array([2,6,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 7 21 30]
[ 3  9 10]
[ 10  90 200]
[2.5 2.5 2. ]


In [70]:
a=np.array([[1,2,3],[6,7,8]])
b=np.array([[4,5],[8,4],[6,5]])
c=np.dot(a,b)
c

array([[ 38,  28],
       [128,  98]])

In [71]:
#transpose r to c , c to r 
mat=np.array([[1,2,3],[6,7,8]])
print(mat.T)

[[1 6]
 [2 7]
 [3 8]]


In [73]:
ar=np.array([33,5,1,2,5,8])
print(np.sort(ar))

[ 1  2  5  5  8 33]


In [82]:
a=np.array([1,2,3])
b=np.array([4,5,7])
c=np.array([8,9,10,11])
print(np.concatenate((a,c)))
print(np.concatenate((b,a)))

[ 1  2  3  8  9 10 11]
[4 5 7 1 2 3]


In [83]:
ar=np.array([33,5,1,2,5,8,2,33])
print(np.unique(ar))

[ 1  2  5  8 33]


In [86]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
ar=np.linspace(1,10,5)
print(ar)

[ 1.    3.25  5.5   7.75 10.  ]
