In [1]:
import numpy as np 
a=np.array([1,2,3,4,5])
print(np.argmax(a))

4


In [3]:
print(np.argmin(a))
      

0


In [4]:
print(np.where(a>3))

(array([3, 4]),)


In [6]:
print(np.cumsum(a))

[ 1  3  6 10 15]


In [7]:
r=np.random.randint(1,20,10)
r

array([ 1,  7, 11, 11,  6, 11,  8, 13, 12, 12])

In [9]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.corrcoef(a,b))

[[1. 1.]
 [1. 1.]]


In [12]:
a=np.array([1,2,3,4,5])
np.save("ps.npy",a)
print(np.load("ps.npy"))

[1 2 3 4 5]


In [14]:
a=np.array([1,2,3,4,5])
print(a[2:4])

[3 4]


In [17]:
print(a[::3])

[1 4]


In [18]:
print(a[::-2])


[5 3 1]


In [19]:
print(a[:-2])

[1 2 3]


In [21]:
arr=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,2]])
print(arr[0:1,1:3])

[[2 3]]


In [22]:
print(arr[:,::2])

[[1 3]
 [3 5]
 [7 9]]


In [23]:
print(arr[:,1:2])

[[2]
 [4]
 [8]]
